### ISSUE TITLE
generate custom DMI table

### ISSUE THREAD

**Issue by tmakatos** [jrgerber/smbios-lib#107]
I need to create custom DMI tables tables for testing purposes, can smbios-lib do that? E.g. create a DMI table that contains a slot with a specified designation.

**Comment by jczuluag** [comment]
Hi @tmakatos: smbios-lib project reads raw [SMBIOS](https://en.wikipedia.org/wiki/BIOS) data from either a device or file and provides the data as an API. It doesn't provides a capability to create those contents, and store them on a 'file'.
