### ISSUE TITLE
Publication of 0.9.1 on crates.io

### ISSUE THREAD

**Issue by ad0** [jrgerber/smbios-lib#112]
When hunting for a segfault on MacOS, I updated dependencies (see #111). It turns out that the bug was not in dependencies, but was already fixed in branch main, probably related to #104. Do you plan to publish 0.9.1 on crates.io anytime soon, for bugfixes and improvements that have been made since 0.9.0?

**Comment by jczuluag** [comment]
@ad0 , great suggestion. Published: https://crates.io/crates/smbios-lib

**Comment by ad0** [comment]
Great ! Thank you
