### ISSUE TITLE
ProcessorFamily missing latest values

### ISSUE THREAD

**Issue by jrgerber** [jrgerber/smbios-lib#70]
The following values are DMTF 3.4.0 values but are missing:
```
118h 280 ARM
119h 281 StrongARM
12Ch 300 6x86
12Dh 301 MediaGX
12Eh 302 MII
140h 320 WinChip
15Eh 350 DSP
1F4h 500 Video Processor
200h 512 RISC-V RV32
201h 513 RISC-V RV64
202h 514 RISC-V RV128
```

**Comment by jczuluag** [comment]
Hi @jrgerber , let me know if  I can take this one.

**Comment by jrgerber** [comment]
> Hi @jrgerber , let me know if I can take this one.

Please do!

**Comment by jczuluag** [comment]
Hi @jrgerber , I was wondering about the [hex values](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf) of the missing values. Seems like 3.4.0 spec has different values for some of the ones that are in this issue. Am I looking at the same table? (table 23)

**Comment by jrgerber** [comment]
> Hi @jrgerber , I was wondering about the [hex values](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf) of the missing values. Seems like 3.4.0 spec has different values for some of the ones that are in this issue. Am I looking at the same table? (table 23)

Yep, 7.5.2 Processor Information — Processor Family, Table 23.

100h-1FFh 256-511 These values are available for assignment, except for the following:
100h 256 ARMv7
101h 257 ARMv8
104h 260 SH-3
105h 261 SH-4
118h 280 ARM
119h 281 StrongARM
12Ch 300 6x86
12Dh 301 MediaGX
12Eh 302 MII
140h 320 WinChip
15Eh 350 DSP
1F4h 500 Video Processor
200h 512 RISC-V RV32
201h 513 RISC-V RV64
202h 514 RISC-V RV128

I'm looking and see what you mean, this is confusing, it looks like more is wrong:
0xFE =&gt; ProcessorFamily::SeeProcessorFamily2,            0x100 =&gt; ProcessorFamily::ARMv7,            0x101 =&gt; ProcessorFamily::ARMv8,            0x102 =&gt; ProcessorFamily::SH3,            0x103 =&gt; ProcessorFamily::SH4,            0x104 =&gt; ProcessorFamily::ARM,            0x105 =&gt; ProcessorFamily::StrongARM,            0x106 =&gt; ProcessorFamily::Cyrix6x86,            0x107 =&gt; ProcessorFamily::MediaGX,            0x108 =&gt; ProcessorFamily::MII,            0x109 =&gt; ProcessorFamily::WinChip,            0x10A =&gt; ProcessorFamily::DSP,            0x10B =&gt; ProcessorFamily::VideoProcessor,            0x10C =&gt; ProcessorFamily::RISCVRV32,            0x10D =&gt; ProcessorFamily::RISCVRV64,            0x10E =&gt; ProcessorFamily::RISCVRV128,
